<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9a7c6b3e487920be91f288b34edd4836
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Defuse\\Crypto\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Defuse\\Crypto\\' => 
        array (
            0 => __DIR__ . '/..' . '/defuse/php-encryption/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9a7c6b3e487920be91f288b34edd4836::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9a7c6b3e487920be91f288b34edd4836::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
